# Generated by Django 5.2.8 on 2025-11-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('avg_rating', models.FloatField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('reputation_index', models.FloatField(default=0)),
                ('sales_total', models.FloatField(default=0)),
                ('last_event', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_event_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
